version: '2'
services:

  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
    restart: always
    working_dir: /opt/app
    volumes:
      - ./app:/opt/app
      - ./app/cron.conf:/etc/cron.d/cron_conf
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - postgres
    command: ["./bin/wait-for-it.sh", "db:5432", "--", "./bin/run.sh"]

  front:
    image: node:13
    restart: always
    ports:
      - 3000:3000
    working_dir: /opt/app
    volumes:
      - ./front:/opt/app
    command: ["./bin/run.sh"]
