# Generated by Django 2.2.6 on 2019-10-21 20:12

from django.db import migrations


def init_currencies(apps, schema_editor):
    Currencies = apps.get_model('converter', 'Currencies')
    Currencies.objects.create(code='CZK', name='Czech Republic Koruna')
    Currencies.objects.create(code='EUR', name='Euro')
    Currencies.objects.create(code='PLN', name='Polish Zloty')
    Currencies.objects.create(code='USD', name='United States Dollar')


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_currencies),
    ]
